WITH SUM_SCORE AS (
	SELECT EMP_NO, SUM(SCORE) AS SCORE
	FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT S.SCORE AS SCORE, E.EMP_NO AS EMP_NO, EMP_NAME, POSITION, EMAIL
FROM  HR_EMPLOYEES E
JOIN SUM_SCORE S
ON E.EMP_NO = S.EMP_NO
WHERE SCORE = (SELECT MAX(SCORE) FROM SUM_SCORE)